// All icons used in the application
export {
  // From @tabler/icons-react
  IconArrowRight,
  IconCode,
  IconCertificate,
  IconRocket,
  IconUsers,
  IconBriefcase,
  IconClock,
  IconCurrencyRupee,
  IconBook,
  IconAppWindow,
  IconSeo,
  IconSun,
  IconMoon,
  IconSearch,
  IconCheck,
  IconStar,
  IconCalendar,
  IconFilter,
  IconAdjustments,
  IconGridDots,
  IconList,
  IconArrowLeft,
  IconTrophy,
  IconSchool,
  IconBulb,
  IconDeviceLaptop,
  IconChartBar,
  IconBrandLinkedin,
  IconBrandTwitter,
  IconHeartHandshake,
  IconTargetArrow,
  IconAward,
  IconQuote,
  IconMail,
  IconPhone,
  IconMapPin,
  IconBrandInstagram,
  IconBrandYoutube,
  IconUpload,
  IconX,
  IconPhoto,
  IconAlertCircle,
  IconEye,
  IconDashboard,
  IconLogout,
} from "@tabler/icons-react";

// Re-export any custom icons here
// export { default as CustomIcon } from './custom-icon';
